# Generated by Django 5.2 on 2025-04-29 17:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('description', models.TextField()),
                ('length_category', models.CharField(choices=[('short', 'Short (<90 min)'), ('normal', 'Normal (90-120 min)'), ('long', 'Long (>120 min)')], max_length=10)),
                ('period_category', models.CharField(choices=[('recent', 'Recent (last 5 years)'), ('modern', 'Modern (last 20 years)'), ('classic', 'Classic (older than 20 years)')], max_length=10)),
                ('duration_minutes', models.IntegerField()),
                ('poster_url', models.URLField(blank=True, max_length=500, null=True)),
                ('imdb_rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('streaming_platform', models.CharField(blank=True, max_length=100, null=True)),
                ('genres', models.ManyToManyField(to='movies.genre')),
                ('languages', models.ManyToManyField(to='movies.language')),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_length', models.CharField(blank=True, choices=[('short', 'Short (<90 min)'), ('normal', 'Normal (90-120 min)'), ('long', 'Long (>120 min)')], max_length=10, null=True)),
                ('preferred_period', models.CharField(blank=True, choices=[('recent', 'Recent (last 5 years)'), ('modern', 'Modern (last 20 years)'), ('classic', 'Classic (older than 20 years)')], max_length=10, null=True)),
                ('preferred_genres', models.ManyToManyField(blank=True, to='movies.genre')),
                ('preferred_languages', models.ManyToManyField(blank=True, to='movies.language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MoodGenreMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1.0)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.genre')),
                ('mood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.mood')),
            ],
            options={
                'unique_together': {('mood', 'genre')},
            },
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'movie')},
            },
        ),
    ]
